### ISSUE TITLE
Latest version isn't work

### ISSUE THREAD

**Issue by alexlukin-softgrad** [pqx/react-frame#2]
Latest version of the library isn't work because of error

`Uncaught TypeError: Cannot delete property 'children' of #<Object>`

This error occures in my test app with React 14 and in the example page
http://pqx.github.io/react-frame/example/

**Comment by wangzuo** [comment]
Yes, there is still some problem with the react 0.14 upgrade.

**Comment by alexlukin-softgrad** [comment]
Will you plan to fix it?

**Comment by wangzuo** [comment]
Yes.
