### ISSUE TITLE
renderFrame this.props is not defined

### ISSUE THREAD

**Issue by olgenn** [pqx/react-frame#26]
![image](https://user-images.githubusercontent.com/2856421/56116062-8fca8900-5f6d-11e9-9299-bd607fc5ae71.png)
Please, add `.bind(this)` for Iframe onLoad callback
<img width="730" alt="react-frame:frame js at master · pqx:react-frame 2019-04-15 11-02-16" src="https://user-images.githubusercontent.com/2856421/56116234-010a3c00-5f6e-11e9-823c-afc13eeeab3d.png">

**Comment by wangzuo** [comment]
fixed in `2.2.12`

**Comment by olgenn** [comment]
@wangzuo Thank you!
